<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WKWIN9528828" ignored="0" name="My Test" tests="2" failures="1" timestamp="19 Nov 2018 03:46:36 GMT" time="28.946" errors="0">
  <testcase name="loginWithValidCredentials" time="8.313" classname="cetera.Automation.tests.MyFirstTest">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.fail(Assert.java:53)
at cetera.Automation.tests.MyFirstTest.loginWithValidCredentials(MyFirstTest.java:26)
at cetera.Automation.testUtils.DynamicRunner.createTestRunner(DynamicRunner.java:133)
... Removed 50 stack frames]]>
    </failure>
  </testcase> <!-- loginWithValidCredentials -->
  <testcase name="loginWithValidCredentialsViral" time="5.515" classname="cetera.Automation.tests.MyFirstTest"/>
</testsuite> <!-- My Test -->
