<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="OMI" name="jameel.banKChalo.testUtils.DynamicRunner" tests="1" failures="0" timestamp="02 Nov 2018 17:53:53 GMT" time="0.063" errors="1">
  <testcase name="createTestRunner" time="0.063" classname="jameel.banKChalo.testUtils.DynamicRunner">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at org.testng.xml.XmlTest.isJUnit(XmlTest.java:281)
at org.testng.xml.DefaultXmlWeaver.asXml(DefaultXmlWeaver.java:153)
at org.testng.xml.XmlWeaver.asXml(XmlWeaver.java:67)
at org.testng.xml.XmlTest.toXml(XmlTest.java:475)
at org.testng.xml.DefaultXmlWeaver.asXml(DefaultXmlWeaver.java:139)
at org.testng.xml.XmlWeaver.asXml(XmlWeaver.java:57)
at org.testng.xml.XmlSuite.toXml(XmlSuite.java:518)
at jameel.banKChalo.testUtils.DynamicRunner.createTestRunner(DynamicRunner.java:121)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- createTestRunner -->
</testsuite> <!-- jameel.banKChalo.testUtils.DynamicRunner -->
